### ISSUE TITLE
post_title empty

### ISSUE THREAD

**Issue by jotnet** [algolia/algoliasearch-wordpress#95] opened 2016-05-19 10:16 UTC
![bez tytulu](https://cloud.githubusercontent.com/assets/8000101/15390309/830f9940-1dbb-11e6-87d5-a4c9e9853a29.png)

Wordpress dont export title, type etc... Where I should search?

**Comment by JanPetr** [comment] 2016-05-19 11:19
Hi @jotnet,
what version of the plugin do you use? Do you use the lastest version from `develop` branch? It should be fixed there.

**Comment by stockwerk5** [comment] 2016-06-26 14:58
Hi @JanPetr , I can confirm @jotnet 's comment having the same issue with the latest develop branch.

**Comment by rayrutjes** [comment] 2016-06-26 16:58
Hey @stockwerk5 and @jotnet , sorry for not being as responsive as we should be on this repository, the reason is that we are working on a new version.

There is currently a private beta program running, if you are interested please send us an email to support+wordpress@algolia.com

**Comment by firasd** [comment] 2016-07-19 14:15
It's because of the way PHP7 interprets syntax

To fix this (so far), in WordPressFetcher.php, I replaced 

`return $this->cast($data->$attribute['name'], $this->contentFieldsNames[$attribute['name']]);`

With this, i.e. adding braces around the object key

`return $this->cast($data->{$attribute['name'}], $this->contentFieldsNames[$attribute['name']]);`

**Comment by rayrutjes** [comment] 2016-07-30 19:11
Hi @jotnet , this issue should be fixed in the new version, 0.2.5 at the time of writing this.
Please note however that this new version is not compatible with 0.0.1 and that the features have changed.

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

We also have a list of [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html)

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please re-open an issue.

**Closed by rayrutjes** 2016-07-30 19:11 UTC
